---
name: Deploy Apps 🚀

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: '12 3 * * *'

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SHINYAPPSIO_ACCOUNT: genentech

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    if: >
      !contains(github.event.commits[0].message, '[skip deploy]')
    strategy:
      matrix:
        directory:
          [
            "RNA-seq",
            "basic-teal"
          ]
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Setup system dependencies for cypress
        run: >
          apt-get update && apt-get install --yes
          libgtk2.0-0 libgbm-dev libnotify-dev libgconf-2-4 xvfb

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set-up npm packages
        shell: bash
        working-directory: ${{ github.event.repository.name }}/${{ matrix.directory }}/js
        run: |
          npm i

      - name: Install app dependencies
        shell: Rscript {0}
        run: |
          setwd("${{ github.event.repository.name }}/${{ matrix.directory }}")
          install.packages('remotes')
          remotes::install_version("rsconnect", "0.8.29")
          remotes::install_version("renv", "1.0.0")
          install.packages(
            renv::dependencies()$Package,
            repos = c(
              Pharmaverse = "https://pharmaverse.r-universe.dev",
              CRAN = "https://cloud.r-project.org",
              BioC = BiocManager::repositories()
            )
          )

      - name: Front end test to check if the app works fine
        if: always()
        uses: cypress-io/github-action@v2
        with:
          working-directory: ${{ github.event.repository.name }}/${{ matrix.directory }}/js
          start: npm run run-app
          wait-on-timeout: 240
          project: ../tests

      - name: Deploy 🖨 ${{ matrix.directory }} 🎨
        shell: Rscript {0}
        run: |
          options(
            repos = c(
              Pharmaverse = "https://pharmaverse.r-universe.dev",
              CRAN = "https://cloud.r-project.org",
              BioC = BiocManager::repositories()
            )
          )
          rsconnect::setAccountInfo(
            name = "${{ env.SHINYAPPSIO_ACCOUNT }}",
            token = "${{ secrets.SHINYAPPSIO_TOKEN }}",
            secret = "${{ secrets.SHINYAPPSIO_SECRET }}",
            server = "shinyapps.io"
          )
          rsconnect::deployApp(
            appDir = "./${{ github.event.repository.name }}/${{ matrix.directory }}",
            appName = rsconnect::generateAppName("${{ matrix.directory }}"),
            appTitle = "${{ matrix.directory }}",
            account = "${{ env.SHINYAPPSIO_ACCOUNT }}",
            upload = TRUE,
            logLevel = "normal",
            lint = FALSE,
            forceUpdate = TRUE
          )
