---
name: Deploy Apps 🚀

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: '12 3 * * *'

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SHINYAPPSIO_ACCOUNT: genentech

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    name: Publish 🗞
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    if: >
      !contains(github.event.commits[0].message, '[skip deploy]')
    strategy:
      matrix:
        directory:
          [
            "RNA-seq",
            "basic-teal",
            "efficacy",
            "exploratory",
            "longitudinal",
            "early-dev",
            "patient-profile",
            "python",
            "safety",
          ]
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      - name: Install app dependencies
        shell: Rscript {0}
        run: |
          setwd("${{ github.event.repository.name }}/${{ matrix.directory }}")
          install.packages('remotes')
          remotes::install_version("rsconnect", "0.8.29")
          remotes::install_version("renv", "1.0.0")
          install.packages(
            renv::dependencies()$Package,
            repos = c(
              Pharmaverse = "https://pharmaverse.r-universe.dev",
              CRAN = "https://cloud.r-project.org",
              BioC = BiocManager::repositories()
            )
          )
      - name: Deploy 🖨 ${{ matrix.directory }} 🎨
        shell: Rscript {0}
        run: |
          options(
            repos = c(
              Pharmaverse = "https://pharmaverse.r-universe.dev",
              CRAN = "https://cloud.r-project.org",
              BioC = BiocManager::repositories()
            )
          )
          rsconnect::setAccountInfo(
            name = "${{ env.SHINYAPPSIO_ACCOUNT }}",
            token = "${{ secrets.SHINYAPPSIO_TOKEN }}",
            secret = "${{ secrets.SHINYAPPSIO_SECRET }}",
            server = "shinyapps.io"
          )
          rsconnect::deployApp(
            appDir = "./${{ github.event.repository.name }}/${{ matrix.directory }}",
            appName = rsconnect::generateAppName("${{ matrix.directory }}"),
            appTitle = "${{ matrix.directory }}",
            account = "${{ env.SHINYAPPSIO_ACCOUNT }}",
            upload = TRUE,
            logLevel = "normal",
            lint = FALSE,
            forceUpdate = TRUE
          )
